services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
    networks:
      - postgresql_project_x

  backend:
    build:
      context: ./ttracker
      dockerfile: Dockerfile
    container_name: ttracker_backend
    restart: always
    env_file:
      - ./ttracker/.env
    ports:
      - '3001:3000'
    environment:
      DATABASE_URL: postgresql://andrew_malinin:s5ixGvXeyi@postgres:5432/project_x_db
    networks:
      - postgresql_project_x

  frontend:
    build:
      context: "./ttracker front"
      dockerfile: Dockerfile
    container_name: ttracker_frontend
    restart: always
    ports:
      - '8081:80'
    networks:
      - postgresql_project_x
    
networks:
  postgresql_project_x:
    external: true